PracticaMVC3/PracticaMVC3/Models/AccesoDatos/Venta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC3.Models.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.DetalleVentaSet = new HashSet<DetalleVentaSet>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaSet> DetalleVentaSet { get; set; }
    }
}

PracticaMVC3/PracticaMVC3/ViewModels/VentaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaMVC3.ViewModels
{
    public class VentaViewModel
    {
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Fecha { get; set; }
        [Required]
        [Range(0, 9999999999999999.99)]
        public Decimal Total { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
    }
}

PracticaMVC3/PracticaMVC3/Controllers/VentaController.cs
using PracticaMVC3.Models.AccesoDatos;
using PracticaMVC3.Models.LogicaNegocio;
using PracticaMVC3.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaMVC3.Controllers
{
    public class VentaController : Controller
    {
        GestorProducto gestorPro = new GestorProducto();
        GestorVenta gestor = new GestorVenta();
        public ActionResult MenuVenta()
        {
            return View();
        }
        public ActionResult ListarVenta()
        {
            var listaVenta = gestor.Listar();
            return View(listaVenta);
        }
        public ActionResult Guardar(Venta venta)
        {
            if (!ModelState.IsValid)
            {
                return View("Crear", venta);
            }
            try
            {
                gestor.Guardar(venta);
                return RedirectToAction("ObtenerLista");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Error");
                return View("Crear", venta);
            }
       
        }
        public ActionResult Crear()
        {
            return View(new VentaViewModel());
        }
        public ActionResult Venta()
        {
            var listaProducto = gestorPro.ObtenerLista();
            return View(listaProducto);
        }
    }
}

PracticaMVC3/PracticaMVC3/Views/Venta/ListarVenta.cshtml
@model List<PracticaMVC3.Models.AccesoDatos.Venta>

<h1>Lista de Ventas</h1>
<table class="table-bordered">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var venta in Model)
        {
            <tr>
                <td>@venta.Fecha</td>
                <td>@venta.Total</td>
            </tr>
        }
    </tbody>
</table>

PracticaMVC3/PracticaMVC3/Views/Venta/MenuVenta.cshtml
@{
    ViewBag.Title = "MenuVenta";
}

<h2>Menu Venta</h2>
<head>

</head>
<body>

    <div>
        
            <ul>
                <li>@Html.ActionLink("Lista de ventas", "ListarVenta", "Venta")</li>
                <li>@Html.ActionLink("Crear Venta", "Crear", "Venta")</li>

            </ul>
      
    </div>
</body>

PracticaMVC3/PracticaMVC3/Views/Venta/Venta.cshtml
@model List<PracticaMVC3.Models.AccesoDatos.Producto>
@{
    ViewBag.Title = "Venta";
}
<body>
    <h2>Venta</h2>
    
    <table class="table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Dni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var producto in Model)
            {
                <tr>
                    <td>@producto.Nombre</td>
                    <td>@producto.Precio</td>
                    <td>@producto.Codigo</td>     
                </tr>
            }
        </tbody>
    </table>
        <label id="lbCodigo">Codigo</label>
        <input type="text" id="txtCodigo" />
        <label id="lbNombre">Nombre</label>
        <input type="text" id="txtNombre" />
        <label id="lbCantidad">Cantidad</label>
        <input type="text" id="txtCantidad" />
        <label id="lbPrecio">Precio</label>
        <input type="text" id="txtPrecio" />
        <input type="button" id="btnCargarVenta" value="Cargar Venta">
        <table style="width:25%" border="1">
            <tr>
                <th>Cantidad</th>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th><input type="button" onclick="BorrarRegistro()"></th>
            </tr>
            <tr></tr>
        </table>
        <label id="lbTotal">Total:</label>
        <label>Cargar Venta Total</label>
        <input type="submit" />
</body>
<script src="~/scripts/Venta.js"></script>