PracticaMVC3/PracticaMVC3/Models/AccesoDatos/Persona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC3.Models.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Dni { get; set; }
        public int Id { get; set; }
    }
}

PracticaMVC3/PracticaMVC3/ViewModels/PersonaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaMVC3.ViewModels
{
    public class PersonaViewModel
    {
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Required]
        public string Dni { get; set; }
        [HiddenInput(DisplayValue =false)]
        public int Id { get; set; }
    }
}

PracticaMVC3/PracticaMVC3/Controllers/PersonaController.cs
using PracticaMVC3.Models.AccesoDatos;
using PracticaMVC3.Models.LogicaNegocio;
using PracticaMVC3.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaMVC3.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        GestorPersona gestor = new GestorPersona();
        public ActionResult ObtenerLista()
        {
            var listaPersona = gestor.ObtenerLista();
            return View(listaPersona);
        }
        public ActionResult Guardar(Persona persona)
        {
            if(!ModelState.IsValid)
            {                
                return View("Crear", persona);
            }
            try
            {
                gestor.Guardar(persona);
                return RedirectToAction("ObtenerLista");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Error");
                return View("Crear", persona);
            }
        }
        public ActionResult Crear()
        {
            return View(new PersonaViewModel());
        }
        public ActionResult PersonaEncontrada(Persona persona)
        {
            return View(persona);
        }
        public ActionResult Eliminar(int id)
        {
            gestor.Eliminar(id);
            return RedirectToAction("ObtenerLista");
        }
        public ActionResult Modificar(int id)
        {
            var personaEncontrada = gestor.ObtenerPorId(id);
            return View(personaEncontrada);
        }
        public ActionResult GuardarModificacion(Persona persona)
        {
            gestor.Modificar(persona);
            return RedirectToAction("ObtenerLista");
        }
        protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.ExceptionHandled = true;
            filterContext.Result = new ViewResult
            {
                ViewName = "/Views/Error/Error.cshtml"
            };
        }
        public ActionResult Busqueda()
        {
            return View();
        }
        public ActionResult DetallePersona(string parametroBusqueda)
        {
            var resultado = gestor.Buscar(parametroBusqueda);
            if(resultado.Count==0)
            {
                ModelState.AddModelError(string.Empty,"No existe la persona esa por favor intente nuevamente");
                return View("Busqueda");
            }
            if(resultado.Count>1)
            {
                return View("ObtenerLista", resultado);
            }
            else
            {
                var persona = resultado.FirstOrDefault();
                var personaViewModel = new PersonaViewModel
                {
                    Nombre=persona.Nombre,
                    Apellido=persona.Apellido,
                    Dni=persona.Dni
                };
                return View(personaViewModel);
            }
        }
        public ActionResult BuscarPartial(string parametroBusqueda)
        {
            try
            {
                var resultado = gestor.Buscar(parametroBusqueda);
                var persona = resultado.FirstOrDefault();
                return PartialView("DetallePersona", persona.ToViewModel());
            }
            catch (Exception ex)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

PracticaMVC3/PracticaMVC3/Views/Persona/Busqueda.cshtml
@{
    ViewBag.Title = "Busqueda";
}

<h2>Busqueda</h2>
@using (Html.BeginForm("DetallePersona", "Persona"))
{
    @Html.ValidationSummary()
    <label>Ingrese alguna caracteristica referida a la persona a buscar</label>
    <input name="parametroBusqueda"/>
    <input type="submit"/>
}

PracticaMVC3/PracticaMVC3/Views/Persona/Crear.cshtml
<h1>Guardar Persona</h1>
<form action="/Persona/Guardar">
    <label for="Nombre">Ingrese el Nombre:</label>
    <input type="text" placeholder="Nombre" maxlength="1000" name="Nombre" id="Nombre" />
    <label for="Apellido">Ingrese el Apellido:</label>
    <input type="text" placeholder="Apellido" maxlength="1000" name="Apellido" id="Apellido" />
    <label for="Dni">Ingrese el Dni:</label>
    <input type="text" placeholder="Dni" maxlength="1000" name="Dni" id="Dni" />
    <input type="submit" />

</form>

PracticaMVC3/PracticaMVC3/Views/Persona/DetallePersona.cshtml
@model PracticaMVC3.ViewModels.PersonaViewModel
@{
    ViewBag.Title = "DetallePersona";
}

<h2>DetallePersona</h2>
<label>Nombre:</label>
<label>@Model.Nombre</label>
<br/>
<label>Apellido:</label>
<label>@Model.Apellido</label>
<br />
<label>Dni:</label>
<label>@Model.Dni</label>
@Html.ActionLink("Volver a Lista","ObtenerLista","Persona")

PracticaMVC3/PracticaMVC3/Views/Persona/Modificar.cshtml
@model  PracticaMVC3.Models.AccesoDatos.Persona
@{
    ViewBag.Title = "Modificar";
}
<h1>Modificar</h1>

<form action="/Persona/GuardarModificacion">
    <br />
    <label>Nombre:</label>
    <input name="Nombre" value="@Model.Nombre" />
    <br />
    <label>Apellido:</label>
    <input name="Apellido" value="@Model.Apellido" />
    <br />
    <label>Dni:</label>
    <input name="Dni" value="@Model.Dni" />

    @Html.Hidden("Id", @Model.Id)
    <br />

    @if (ViewBag.Mensaje != null)
    {
        <h3>View.Bag.Mensaje</h3>
    }
    <input type="submit" value="Guardar" />

</form>

PracticaMVC3/PracticaMVC3/Views/Persona/ObtenerLista.cshtml
@model List<PracticaMVC3.Models.AccesoDatos.Persona>

<h1>Lista de Personas</h1>
<table class="table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Dni</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var persona in Model)
        {
            <tr>
                <td>@persona.Nombre</td>
                <td>@persona.Apellido</td>
                <td>@persona.Dni</td>
                <td>@Html.ActionLink("Modificar", "Modificar", new { id = @persona.Id })</td>
                <td>@Html.ActionLink("Eliminar", "Eliminar", new { id = @persona.Id })</td>
                <td></td>
            </tr>
        }
       // @Html.ActionLink("Buscar","Busqueda", "Persona")
        </tbody>
</table>
<input id="txt-prueba" type="text"value="prueba" />
<input id="btn-buscar"type="button"value="Buscar"/>
<div id="div-resultado">a</div>
<script src="~/scripts/jquery-1.10.2.js"></script>
<script src="~/scripts/bootstrap.min.js"></script>
<script src="~/scripts/Listar.js"></script>