PracticaMVC3/PracticaMVC3/Models/AccesoDatos/Proveedor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC3.Models.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Codigo { get; set; }
        public int Id { get; set; }
    }
}

PracticaMVC3/PracticaMVC3/ViewModels/ProveedorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaMVC3.ViewModels
{
    public class ProveedorViewModel
    {
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Direccion { get; set; }
        [Required]
        public string Codigo { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
    }
}

PracticaMVC3/PracticaMVC3/Controllers/ProveedorController.cs
using PracticaMVC3.Models.AccesoDatos;
using PracticaMVC3.Models.LogicaNegocio;
using PracticaMVC3.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticaMVC3.Controllers
{
    public class ProveedorController : Controller
    {
        // GET: Proveedor
        GestorProveedor gestor = new GestorProveedor();
        public ActionResult ObtenerLista()
        {
            var listaProveedor = gestor.ObtenerLista();
            return View(listaProveedor);
        }
        public ActionResult Guardar(Proveedor proveedor)
        {
            if (!ModelState.IsValid)
            {
                return View("Crear", proveedor);
            }
            try
            {
                gestor.Guardar(proveedor);
                return RedirectToAction("ObtenerLista");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Error");
                return View("Crear", proveedor);
            }
        }
        public ActionResult Crear()
        {
            return View();
        }
        public ActionResult Eliminar(int id)
        {
            gestor.Eliminar(id);
            return RedirectToAction("ObtenerLista");
        }
        public ActionResult Modificar(int id)
        {
            var proveedorEncontrado = gestor.ObtenerPorId(id);
            return View(proveedorEncontrado);
        }
        public ActionResult GuardarModificacion(Proveedor proveedor)
        {
            gestor.Modificar(proveedor);
            return RedirectToAction("ObtenerLista");
        }
        protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.ExceptionHandled = true;
            filterContext.Result = new ViewResult
            {
                ViewName = "/Views/Error/Error.cshtml"
            };
        }
        public ActionResult Busqueda()
        {
            return View();
        }
        public ActionResult DetalleProveedor(string parametroBusqueda)
        {
            var resultado = gestor.Buscar(parametroBusqueda);
            if (resultado.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "No existe la persona esa por favor intente nuevamente");
                return View("Busqueda");
            }
            if (resultado.Count > 1)
            {
                return View("ObtenerLista", resultado);
            }
            else
            {
                var proveedor = resultado.FirstOrDefault();
                var proveedorViewModel = new ProveedorViewModel
                {
                    Nombre = proveedor.Nombre,
                    Direccion = proveedor.Direccion,
                    Codigo = proveedor.Codigo
                };
                return View(proveedorViewModel);
            }
        }
        public ActionResult BuscarPartial(string parametroBusqueda)
        {
            try
            {
                var resultado = gestor.Buscar(parametroBusqueda);
                var proveedor = resultado.FirstOrDefault();
                return PartialView("DetalleProducto", proveedor.ToViewModel());
            }
            catch (Exception ex)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

PracticaMVC3/PracticaMVC3/Views/Proveedor/BuscarPorNombre.cshtml
<h1>Buscar Producto</h1>
<form action="/Producto/BuscarPorNombre">
    <label for="Nombre">Ingrese el Nombre del Proveedor a encontrar:</label>
    <input type="text" placeholder="Nombre" maxlength="1000" name="Nombre" id="Nombre" />
    <input type="submit" />
    <label></label>

</form>

PracticaMVC3/PracticaMVC3/Views/Proveedor/Busqueda.cshtml
@{
    ViewBag.Title = "Busqueda";
}

<h2>Busqueda</h2>
@using (Html.BeginForm("DetalleProveedor", "Proveedor"))
{
    @Html.ValidationSummary()
    <label>Ingrese alguna caracteristica referida a la persona a buscar</label>
    <input name="parametroBusqueda" />
    <input type="submit" />
}

PracticaMVC3/PracticaMVC3/Views/Proveedor/Crear.cshtml
<h1>Guardar Producto</h1>
<form action="/Proveedor/Guardar">
    <label for="Nombre">Ingrese el Nombre:</label>
    <input type="text" placeholder="Nombre" maxlength="1000" name="Nombre" id="Nombre" />
    <label for="Direccion">Ingrese la Direccion:</label>
    <input type="text" placeholder="Direccion" maxlength="1000" name="Direccion" id="Direccion" />
    <label for="Codigo">Ingrese el Codigo</label>
    <input type="text" placeholder="Nombre" maxlength="1000" name="Codigo" id="Codigo" />
    <input type="submit" />

</form>

PracticaMVC3/PracticaMVC3/Views/Proveedor/DetalleProveedor.cshtml
@model PracticaMVC3.ViewModels.ProveedorViewModel
@{
    ViewBag.Title = "DetalleProveedor";
}

<h2>DetalleProveedor</h2>
<label>Nombre:</label>
<label>@Model.Nombre</label>
<br />
<label>Apellido:</label>
<label>@Model.Direccion</label>
<br />
<label>Dni:</label>
<label>@Model.Codigo</label>
@Html.ActionLink("Volver a Lista", "ObtenerLista", "Proveedor")

PracticaMVC3/PracticaMVC3/Views/Proveedor/Modificar.cshtml
@model  PracticaMVC3.Models.AccesoDatos.Proveedor
@{
    ViewBag.Title = "Modificar";
}
<h1>Modificar</h1>
<form action="/Proveedor/GuardarModificacion">
    <br />
    <label>Nombre:</label>
    <input name="Nombre" value="@Model.Nombre" />
    <br />
    <label>Apellido:</label>
    <input name="Direccion" value="@Model.Direccion" />
    <br />
    <label>Dni:</label>
    <input name="Codigo" value="@Model.Codigo" />

    @Html.Hidden("Id", @Model.Id)
    <br />

    @if (ViewBag.Mensaje != null)
    {
        <h3>View.Bag.Mensaje</h3>
    }
    <input type="submit" value="Guardar" />

</form>

PracticaMVC3/PracticaMVC3/Views/Proveedor/ObtenerLista.cshtml
@model List<PracticaMVC3.Models.AccesoDatos.Proveedor>

<h1>Lista de Proveedor</h1>
<table class="table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Codigo</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var proveedor in Model)
        {
            <tr>
                <td>@proveedor.Nombre</td>
                <td>@proveedor.Direccion</td>
                <td>@proveedor.Codigo</td>
                <td>@Html.ActionLink("Modificar", "Modificar", new { id = @proveedor.Id })</td>
                <td>@Html.ActionLink("Eliminar", "Eliminar", new { id = @proveedor.Id })</td>
            </tr>
        }
        @Html.ActionLink("Buscar", "Busqueda", "Proveedor")
    </tbody>
</table>
<input id="txt-prueba" type="text" value="prueba" />
<input id="btn-buscar" type="button" value="Buscar" />
<div id="div-resultado"></div>
<script src="~/scripts/jquery-1.10.2.js"></script>
<script src="~/scripts/bootstrap.min.js"></script>
<script src="~/scripts/Listar-Proveedor.js"></script>